require:
  - standard/cop/semantic_blocks
  - rubocop-md
  - ruby-next/rubocop

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 2.7
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*.gemfile'
    - 'gemfiles/vendor/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - '*.gemspec'
    - 'lib/.rbnext/**/*'

Lint/DuplicateMethods:
  Exclude:
    - '**/*.md'

Layout/EmptyLineBetweenDefs:
  Exclude:
    - '**/*.md'
