require:
  - standard/cop/semantic_blocks
  - rubocop-md

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*.gemfile'
    - 'gemfiles/vendor/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - '*.gemspec'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/NumericLiterals:
  Enabled: false

Lint/DuplicateMethods:
  Exclude:
    - '**/*.md'

Layout/EmptyLineBetweenDefs:
  Exclude:
    - '**/*.md'
